export const CREATE_PROFILE_REQ = 'CREATE_PROFILE_REQ';
export const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS';
export const CREATE_PROFILE_ERROR = 'CREATE_PROFILE_ERROR';

export const UPDATE_PROFILE_REQ = 'UPDATE_PROFILE_REQ';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';

export const FETCH_BAND_PROFILE_REQ = 'FETCH_BAND_PROFILE_REQ';
export const FETCH_BAND_PROFILE_SUCCESS = 'FETCH_BAND_PROFILE_SUCCESS';
export const FETCH_BAND_PROFILE_ERROR = 'FETCH_BAND_PROFILE_ERROR';

export const FETCH_MUSICIAN_PROFILE_REQ = 'FETCH_MUSICIAN_PROFILE_REQ';
export const FETCH_MUSICIAN_PROFILE_SUCCESS = 'FETCH_MUSICIAN_PROFILE_SUCCESS';
export const FETCH_MUSICIAN_PROFILE_ERROR = 'FETCH_MUSICIAN_PROFILE_ERROR';

export const FETCH_MATCHES_REQ = 'FETCH_MATCHES_REQ';
export const FETCH_MATCHES_SUCCESS = 'FETCH_MATCHES_SUCCESS';
export const FETCH_MATCHES_ERROR = 'FETCH_MATCHES_ERROR';

export const CREATE_CONNECTION_REQ = 'CREATE_CONNECTION_REQ';
export const CREATE_CONNECTION_SUCCESS = 'CREATE_CONNECTION_SUCCESS';
export const CREATE_CONNECTION_ERROR = 'CREATE_CONNECTION_ERROR';

export const CREATE_DO_NOT_DISPLAY_REQ = 'CREATE_DO_NOT_DISPLAY_REQ';
export const CREATE_DO_NOT_DISPLAY_SUCCESS = 'CREATE_DO_NOT_DISPLAY_SUCCESS';
export const CREATE_DO_NOT_DISPLAY_ERROR = 'CREATE_DO_NOT_DISPLAY_ERROR';

export const FETCH_GENRES_REQ = 'FETCH_GENRES_REQ';
export const FETCH_GENRES_SUCCESS = 'FETCH_GENRES_SUCCESS';
export const FETCH_GENRES_ERROR = 'FETCH_GENRES_ERROR';

export const FETCH_INSTRUMENTS_REQ = 'FETCH_INSTRUMENTS_REQ';
export const FETCH_INSTRUMENTS_SUCCESS = 'FETCH_INSTRUMENTS_SUCCESS';
export const FETCH_INSTRUMENTS_ERROR = 'FETCH_INSTRUMENTS_ERROR';

export const FETCH_I_LIKE_REQ = 'FETCH_I_LIKE_REQ';
export const FETCH_I_LIKE_SUCCESS = 'FETCH_I_LIKE_SUCCESS';
export const FETCH_I_LIKE_ERROR = 'FETCH_I_LIKE_ERROR';

export const FETCH_LIKES_ME_REQ = 'FETCH_LIKES_ME_REQ';
export const FETCH_LIKES_ME_SUCCESS = 'FETCH_LIKES_ME_SUCCESS';

