
export const CREATE_CONNECTION_REQ = 'CREATE_CONNECTION_REQ';
export const CREATE_CONNECTION_SUCCESS = 'CREATE_CONNECTION_SUCCESS';
export const CREATE_CONNECTION_ERROR = 'CREATE_CONNECTION_ERROR';

export const FETCH_GENRES_REQ = 'FETCH_GENRES_REQ';
export const FETCH_GENRES_SUCCESS = 'FETCH_GENRES_SUCCESS';
export const FETCH_GENRES_ERROR = 'FETCH_GENRES_ERROR';

export const FETCH_INSTRUMENTS_REQ = 'FETCH_INSTRUMENTS_REQ';
export const FETCH_INSTRUMENTS_SUCCESS = 'FETCH_INSTRUMENTS_SUCCESS';
export const FETCH_INSTRUMENTS_ERROR = 'FETCH_INSTRUMENTS_ERROR';

export const FETCH_MATCHES_REQ = 'FETCH_MATCHES_REQ';
export const FETCH_MATCHES_SUCCESS = 'FETCH_MATCHES_SUCCESS';
export const FETCH_MATCHES_ERROR = 'FETCH_MATCHES_ERROR';

export const FETCH_MY_HEAVEN_REQ = 'FETCH_MY_HEAVEN_REQ';
export const FETCH_MY_HEAVEN_SUCCESS = 'FETCH_MY_HEAVEN_SUCCESS';
export const FETCH_MY_HEAVEN_ERROR = 'FETCH_MY_HEAVEN_ERROR';

export const FETCH_MY_HELL_REQ = 'FETCH_MY_HELL_REQ';
export const FETCH_MY_HELL_SUCCESS = 'FETCH_MY_HELL_SUCCESS';
export const FETCH_MY_HELL_ERROR = 'FETCH_MY_HELL_ERROR';

export const FETCH_THEIR_HEAVEN_REQ = 'FETCH_THEIR_HEAVEN_REQ';
export const FETCH_THEIR_HEAVEN_SUCCESS = 'FETCH_THEIR_HEAVEN_SUCCESS';
export const FETCH_THEIR_HEAVEN_ERROR = 'FETCH_THEIR_HEAVEN_ERROR';

//actions.createProfile
export const CREATE_PROFILE_REQ = 'CREATE_PROFILE_REQ';
export const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS';
export const CREATE_PROFILE_ERROR = 'CREATE_PROFILE_ERROR';

//actions.updateProfile
export const UPDATE_PROFILE_REQ = 'UPDATE_PROFILE_REQ';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';

//actions.fetchProfile
export const FETCH_PROFILE_REQ = 'FETCH_PROFILE_REQ';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_ERROR = 'FETCH_PROFILE_ERROR';







