export const CREATE_PROFILE_REQ = 'CREATE_PROFILE_REQ';
export const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS';
export const CREATE_PROFILE_ERROR = 'CREATE_PROFILE_ERROR';

export const UPDATE_PROFILE_REQ = 'UPDATE_PROFILE_REQ';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';

export const FETCH_BAND_PROFILE_REQ = 'FETCH_BAND_PROFILE_REQ';
export const FETCH_BAND_PROFILE_SUCCESS = 'FETCH_BAND_PROFILE_SUCCESS';
export const FETCH_BAND_PROFILE_ERROR = 'FETCH_BAND_PROFILE_ERROR';

export const FETCH_MUSICIAN_PROFILE_REQ = 'FETCH_MUSICIAN_PROFILE_REQ';
export const FETCH_MUSICIAN_PROFILE_SUCCESS = 'FETCH_MUSICIAN_PROFILE_SUCCESS';
export const FETCH_MUSICIAN_PROFILE_ERROR = 'FETCH_MUSICIAN_PROFILE_ERROR';

export const FETCH_MATCHES_REQ = 'FETCH_MATCHES_REQ';
export const FETCH_MATCHES_SUCCESS = 'FETCH_MATCHES_SUCCESS';
export const FETCH_MATCHES_ERROR = 'FETCH_MATCHES_ERROR';